### PR TITLE
Added identity and other known errors

### LINKED ISSUE #22: Add missing `ApiErrorCode`s
Already done in https://github.com/wultra/networking-apple, so just copy them.

### PR DESCRIPTION
**Pull request by kober32**
Resolved #22

### CODE REVIEW

**Comment by kober32** [comment]
Force push to trigger build again, which was dormant.

**Review by hvge — APPROVED** [review]
Looks OK

**Review by romanstrobl — CHANGES_REQUESTED** [review]
I am missing a couple of error codes:
- `DOCUMENT_SUBMIT_FAILED` - when mobile app resubmits a document which is not known on server or submits document during invalid phase or other problem with document submission
- `ONBOARDING_PROCESS_LIMIT_REACHED` - when a process limit is reached (e.g. max failed attempts reached for identity verification or max error score reached)
- `IDENTITY_VERIFICATION_LIMIT_REACHED` - when an identity verification limit is reached (e.g. max failed attempts reached for document upload)

**Comment by kober32** [comment]
@romanstrobl  -> all errors you mentioned are there 🤔

**Comment by romanstrobl** [comment]
> @romanstrobl -> all errors you mentioned are there 🤔

Apologies, I didn't see them in the diff. Approved 👍

**Review by romanstrobl — APPROVED** [review]
Looks OK.

**Pull request merged**
